### PR TITLE
Update ActiveRecord dependency for Rails 7

### PR DESCRIPTION
**Pull request by lylo**
Rails 7 is close to being released. This PR adds support for `ActiveRecord` 7.x. to the gemspec.

### CODE REVIEW

**Comment by jarednorman** [comment]
Thanks. I think we also need to update the GitHub Actions workflows to ensure tests run against the new version.

**Comment by lylo** [comment]
Oops, thanks! I'll take a look later 😃

**Comment by lylo** [comment]
@jarednorman I've pushed another change that includes Rails edge. Alternatively I could add `7.0.0.rc1` explicitly. I added 6.1 as well.

**Comment by jarednorman** [comment]
That seems reasonable, thanks!

**Comment by lylo** [comment]
Apologies, I messed the first commit up. I've now rectified that and clarified it works locally. Should be good to run the workflows now.

**Comment by jarednorman** [comment]
The failures seem unrelated to your pull request and appear to something to do with `with_model` compatibility. Thanks for this change! 🙏🏻

**Pull request merged**
